"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .list import ListT, ListTTypedDict
from enum import Enum
from growth_machine_sdk_attio_python.types import BaseModel
from growth_machine_sdk_attio_python.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetV2ListsListRequestTypedDict(TypedDict):
    list: str


class GetV2ListsListRequest(BaseModel):
    list: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class GetV2ListsListType(str, Enum):
    INVALID_REQUEST_ERROR = "invalid_request_error"


class GetV2ListsListCode(str, Enum):
    NOT_FOUND = "not_found"


class GetV2ListsListResponseTypedDict(TypedDict):
    r"""Success"""

    data: ListTTypedDict


class GetV2ListsListResponse(BaseModel):
    r"""Success"""

    data: ListT
