"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .object import Object, ObjectTypedDict
from enum import Enum
from growth_machine_sdk_attio_python.types import BaseModel
from growth_machine_sdk_attio_python.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetV2ObjectsObjectRequestTypedDict(TypedDict):
    object: str


class GetV2ObjectsObjectRequest(BaseModel):
    object: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class GetV2ObjectsObjectType(str, Enum):
    INVALID_REQUEST_ERROR = "invalid_request_error"


class GetV2ObjectsObjectCode(str, Enum):
    NOT_FOUND = "not_found"


class GetV2ObjectsObjectResponseTypedDict(TypedDict):
    r"""Success"""

    data: ObjectTypedDict


class GetV2ObjectsObjectResponse(BaseModel):
    r"""Success"""

    data: Object
