"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .status import Status, StatusTypedDict
from enum import Enum
from growth_machine_sdk_attio_python.types import BaseModel
from growth_machine_sdk_attio_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetV2TargetIdentifierAttributesAttributeStatusesTarget(str, Enum):
    r"""Whether the attribute is on an object or a list. Please note that the company and people objects do not support status attributes at this time."""

    LISTS = "lists"
    OBJECTS = "objects"


class GetV2TargetIdentifierAttributesAttributeStatusesRequestTypedDict(TypedDict):
    target: GetV2TargetIdentifierAttributesAttributeStatusesTarget
    r"""Whether the attribute is on an object or a list. Please note that the company and people objects do not support status attributes at this time."""
    identifier: str
    attribute: str
    show_archived: NotRequired[bool]


class GetV2TargetIdentifierAttributesAttributeStatusesRequest(BaseModel):
    target: Annotated[
        GetV2TargetIdentifierAttributesAttributeStatusesTarget,
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Whether the attribute is on an object or a list. Please note that the company and people objects do not support status attributes at this time."""

    identifier: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    attribute: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    show_archived: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False


class GetV2TargetIdentifierAttributesAttributeStatusesType(str, Enum):
    INVALID_REQUEST_ERROR = "invalid_request_error"


class GetV2TargetIdentifierAttributesAttributeStatusesCode(str, Enum):
    NOT_FOUND = "not_found"


class GetV2TargetIdentifierAttributesAttributeStatusesResponseTypedDict(TypedDict):
    r"""Success"""

    data: List[StatusTypedDict]


class GetV2TargetIdentifierAttributesAttributeStatusesResponse(BaseModel):
    r"""Success"""

    data: List[Status]
