"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .thread import Thread, ThreadTypedDict
from enum import Enum
from growth_machine_sdk_attio_python.types import BaseModel
from growth_machine_sdk_attio_python.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetV2ThreadsThreadIDRequestTypedDict(TypedDict):
    thread_id: str


class GetV2ThreadsThreadIDRequest(BaseModel):
    thread_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class GetV2ThreadsThreadIDType(str, Enum):
    INVALID_REQUEST_ERROR = "invalid_request_error"


class GetV2ThreadsThreadIDCode(str, Enum):
    NOT_FOUND = "not_found"


class GetV2ThreadsThreadIDResponseTypedDict(TypedDict):
    r"""Success"""

    data: ThreadTypedDict


class GetV2ThreadsThreadIDResponse(BaseModel):
    r"""Success"""

    data: Thread
