"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    delete_v2_tasks_task_id_op as models_delete_v2_tasks_task_id_op,
)
from growth_machine_sdk_attio_python.types import BaseModel


class DeleteV2TasksTaskIDNotFoundErrorData(BaseModel):
    status_code: float

    type: models_delete_v2_tasks_task_id_op.DeleteV2TasksTaskIDType

    code: models_delete_v2_tasks_task_id_op.DeleteV2TasksTaskIDCode

    message: str


class DeleteV2TasksTaskIDNotFoundError(Exception):
    r"""Not Found"""

    data: DeleteV2TasksTaskIDNotFoundErrorData

    def __init__(self, data: DeleteV2TasksTaskIDNotFoundErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, DeleteV2TasksTaskIDNotFoundErrorData)
