"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    get_v2_target_identifier_attributes_attribute_statusesop as models_get_v2_target_identifier_attributes_attribute_statusesop,
)
from growth_machine_sdk_attio_python.types import BaseModel


class GetV2TargetIdentifierAttributesAttributeStatusesNotFoundErrorData(BaseModel):
    status_code: float

    type: models_get_v2_target_identifier_attributes_attribute_statusesop.GetV2TargetIdentifierAttributesAttributeStatusesType

    code: models_get_v2_target_identifier_attributes_attribute_statusesop.GetV2TargetIdentifierAttributesAttributeStatusesCode

    message: str


class GetV2TargetIdentifierAttributesAttributeStatusesNotFoundError(Exception):
    r"""Not Found"""

    data: GetV2TargetIdentifierAttributesAttributeStatusesNotFoundErrorData

    def __init__(
        self, data: GetV2TargetIdentifierAttributesAttributeStatusesNotFoundErrorData
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, GetV2TargetIdentifierAttributesAttributeStatusesNotFoundErrorData
        )
