"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    get_v2_objects_object_records_record_id_op as models_get_v2_objects_object_records_record_id_op,
)
from growth_machine_sdk_attio_python.types import BaseModel


class GetV2ObjectsObjectRecordsRecordIDNotFoundErrorData(BaseModel):
    status_code: float

    type: models_get_v2_objects_object_records_record_id_op.GetV2ObjectsObjectRecordsRecordIDNotFoundType

    code: models_get_v2_objects_object_records_record_id_op.GetV2ObjectsObjectRecordsRecordIDCode

    message: str


class GetV2ObjectsObjectRecordsRecordIDNotFoundError(Exception):
    r"""Not Found"""

    data: GetV2ObjectsObjectRecordsRecordIDNotFoundErrorData

    def __init__(self, data: GetV2ObjectsObjectRecordsRecordIDNotFoundErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, GetV2ObjectsObjectRecordsRecordIDNotFoundErrorData
        )
