"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    get_v2_objects_object_records_record_id_attributes_attribute_valuesop as models_get_v2_objects_object_records_record_id_attributes_attribute_valuesop,
)
from growth_machine_sdk_attio_python.types import BaseModel


class GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundErrorData(
    BaseModel
):
    status_code: float

    type: models_get_v2_objects_object_records_record_id_attributes_attribute_valuesop.GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundType

    code: models_get_v2_objects_object_records_record_id_attributes_attribute_valuesop.GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundCode

    message: str


class GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundError(
    Exception
):
    r"""Not Found"""

    data: GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundErrorData

    def __init__(
        self,
        data: GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundErrorData,
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data,
            GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundErrorData,
        )


class GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesValidationTypeErrorData(
    BaseModel
):
    status_code: float

    type: models_get_v2_objects_object_records_record_id_attributes_attribute_valuesop.GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesBadRequestType

    code: models_get_v2_objects_object_records_record_id_attributes_attribute_valuesop.GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesCodeValidationType

    message: str


class GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesValidationTypeError(
    Exception
):
    r"""Bad Request"""

    data: GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesValidationTypeErrorData

    def __init__(
        self,
        data: GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesValidationTypeErrorData,
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data,
            GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesValidationTypeErrorData,
        )
