"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    get_v2_lists_list_entries_entry_id_attributes_attribute_valuesop as models_get_v2_lists_list_entries_entry_id_attributes_attribute_valuesop,
)
from growth_machine_sdk_attio_python.types import BaseModel


class GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundErrorData(BaseModel):
    status_code: float

    type: models_get_v2_lists_list_entries_entry_id_attributes_attribute_valuesop.GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundType

    code: models_get_v2_lists_list_entries_entry_id_attributes_attribute_valuesop.GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundCode

    message: str


class GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundError(Exception):
    r"""Not Found"""

    data: GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundErrorData

    def __init__(
        self,
        data: GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundErrorData,
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data,
            GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundErrorData,
        )


class GetV2ListsListEntriesEntryIDAttributesAttributeValuesValidationTypeErrorData(
    BaseModel
):
    status_code: float

    type: models_get_v2_lists_list_entries_entry_id_attributes_attribute_valuesop.GetV2ListsListEntriesEntryIDAttributesAttributeValuesBadRequestType

    code: models_get_v2_lists_list_entries_entry_id_attributes_attribute_valuesop.GetV2ListsListEntriesEntryIDAttributesAttributeValuesCodeValidationType

    message: str


class GetV2ListsListEntriesEntryIDAttributesAttributeValuesValidationTypeError(
    Exception
):
    r"""Bad Request"""

    data: GetV2ListsListEntriesEntryIDAttributesAttributeValuesValidationTypeErrorData

    def __init__(
        self,
        data: GetV2ListsListEntriesEntryIDAttributesAttributeValuesValidationTypeErrorData,
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data,
            GetV2ListsListEntriesEntryIDAttributesAttributeValuesValidationTypeErrorData,
        )
