"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    get_v2_tasks_task_id_op as models_get_v2_tasks_task_id_op,
)
from growth_machine_sdk_attio_python.types import BaseModel


class GetV2TasksTaskIDNotFoundErrorData(BaseModel):
    status_code: float

    type: models_get_v2_tasks_task_id_op.GetV2TasksTaskIDType

    code: models_get_v2_tasks_task_id_op.GetV2TasksTaskIDCode

    message: str


class GetV2TasksTaskIDNotFoundError(Exception):
    r"""Not Found"""

    data: GetV2TasksTaskIDNotFoundErrorData

    def __init__(self, data: GetV2TasksTaskIDNotFoundErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, GetV2TasksTaskIDNotFoundErrorData)
