"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    patch_v2_objects_object_op as models_patch_v2_objects_object_op,
)
from growth_machine_sdk_attio_python.types import BaseModel


class PatchV2ObjectsObjectSlugConflictErrorData(BaseModel):
    status_code: float

    type: models_patch_v2_objects_object_op.PatchV2ObjectsObjectConflictType

    code: models_patch_v2_objects_object_op.PatchV2ObjectsObjectConflictCode

    message: str


class PatchV2ObjectsObjectSlugConflictError(Exception):
    r"""Conflict"""

    data: PatchV2ObjectsObjectSlugConflictErrorData

    def __init__(self, data: PatchV2ObjectsObjectSlugConflictErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, PatchV2ObjectsObjectSlugConflictErrorData)


class PatchV2ObjectsObjectNotFoundErrorData(BaseModel):
    status_code: float

    type: models_patch_v2_objects_object_op.PatchV2ObjectsObjectNotFoundType

    code: models_patch_v2_objects_object_op.PatchV2ObjectsObjectNotFoundCode

    message: str


class PatchV2ObjectsObjectNotFoundError(Exception):
    r"""Not Found"""

    data: PatchV2ObjectsObjectNotFoundErrorData

    def __init__(self, data: PatchV2ObjectsObjectNotFoundErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, PatchV2ObjectsObjectNotFoundErrorData)


class PatchV2ObjectsObjectValidationTypeErrorData(BaseModel):
    status_code: float

    type: models_patch_v2_objects_object_op.PatchV2ObjectsObjectBadRequestType

    code: models_patch_v2_objects_object_op.PatchV2ObjectsObjectCodeValidationType

    message: str


class PatchV2ObjectsObjectValidationTypeError(Exception):
    r"""Bad Request"""

    data: PatchV2ObjectsObjectValidationTypeErrorData

    def __init__(self, data: PatchV2ObjectsObjectValidationTypeErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, PatchV2ObjectsObjectValidationTypeErrorData
        )
