"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    patch_v2_target_identifier_attributes_attribute_statuses_status_op as models_patch_v2_target_identifier_attributes_attribute_statuses_status_op,
)
from growth_machine_sdk_attio_python.types import BaseModel


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictErrorData(
    BaseModel
):
    status_code: float

    type: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusConflictType

    code: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusConflictCode

    message: str


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictError(
    Exception
):
    r"""Conflict"""

    data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictErrorData

    def __init__(
        self,
        data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictErrorData,
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data,
            PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictErrorData,
        )


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundErrorData(
    BaseModel
):
    status_code: float

    type: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundType

    code: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundCode

    message: str


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundError(Exception):
    r"""Not Found"""

    data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundErrorData

    def __init__(
        self,
        data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundErrorData,
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data,
            PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundErrorData,
        )


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusValueNotFoundErrorData(
    BaseModel
):
    status_code: float

    type: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusBadRequestType

    code: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusCodeValueNotFound

    message: str


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusValueNotFoundError(
    Exception
):
    r"""Bad Request"""

    data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusValueNotFoundErrorData

    def __init__(
        self,
        data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusValueNotFoundErrorData,
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data,
            PatchV2TargetIdentifierAttributesAttributeStatusesStatusValueNotFoundErrorData,
        )
