"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    patch_v2_tasks_task_id_op as models_patch_v2_tasks_task_id_op,
)
from growth_machine_sdk_attio_python.types import BaseModel


class PatchV2TasksTaskIDNotFoundErrorData(BaseModel):
    status_code: float

    type: models_patch_v2_tasks_task_id_op.PatchV2TasksTaskIDNotFoundType

    code: models_patch_v2_tasks_task_id_op.PatchV2TasksTaskIDNotFoundCode

    message: str


class PatchV2TasksTaskIDNotFoundError(Exception):
    r"""Not Found"""

    data: PatchV2TasksTaskIDNotFoundErrorData

    def __init__(self, data: PatchV2TasksTaskIDNotFoundErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, PatchV2TasksTaskIDNotFoundErrorData)


class PatchV2TasksTaskIDValidationTypeErrorData(BaseModel):
    status_code: float

    type: models_patch_v2_tasks_task_id_op.PatchV2TasksTaskIDBadRequestType

    code: models_patch_v2_tasks_task_id_op.PatchV2TasksTaskIDCodeValidationType

    message: str


class PatchV2TasksTaskIDValidationTypeError(Exception):
    r"""Bad Request"""

    data: PatchV2TasksTaskIDValidationTypeErrorData

    def __init__(self, data: PatchV2TasksTaskIDValidationTypeErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, PatchV2TasksTaskIDValidationTypeErrorData)
