"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    post_v2_objectsop as models_post_v2_objectsop,
)
from growth_machine_sdk_attio_python.types import BaseModel


class PostV2ObjectsSlugConflictErrorData(BaseModel):
    status_code: float

    type: models_post_v2_objectsop.PostV2ObjectsType

    code: models_post_v2_objectsop.PostV2ObjectsCode

    message: str


class PostV2ObjectsSlugConflictError(Exception):
    r"""Conflict"""

    data: PostV2ObjectsSlugConflictErrorData

    def __init__(self, data: PostV2ObjectsSlugConflictErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, PostV2ObjectsSlugConflictErrorData)
