"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    post_v2_target_identifier_attributesop as models_post_v2_target_identifier_attributesop,
)
from growth_machine_sdk_attio_python.types import BaseModel


class PostV2TargetIdentifierAttributesSlugConflictErrorData(BaseModel):
    status_code: float

    type: models_post_v2_target_identifier_attributesop.PostV2TargetIdentifierAttributesConflictType

    code: models_post_v2_target_identifier_attributesop.PostV2TargetIdentifierAttributesConflictCode

    message: str


class PostV2TargetIdentifierAttributesSlugConflictError(Exception):
    r"""Conflict"""

    data: PostV2TargetIdentifierAttributesSlugConflictErrorData

    def __init__(self, data: PostV2TargetIdentifierAttributesSlugConflictErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, PostV2TargetIdentifierAttributesSlugConflictErrorData
        )


class PostV2TargetIdentifierAttributesNotFoundErrorData(BaseModel):
    status_code: float

    type: models_post_v2_target_identifier_attributesop.PostV2TargetIdentifierAttributesNotFoundType

    code: models_post_v2_target_identifier_attributesop.PostV2TargetIdentifierAttributesNotFoundCode

    message: str


class PostV2TargetIdentifierAttributesNotFoundError(Exception):
    r"""Not Found"""

    data: PostV2TargetIdentifierAttributesNotFoundErrorData

    def __init__(self, data: PostV2TargetIdentifierAttributesNotFoundErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, PostV2TargetIdentifierAttributesNotFoundErrorData
        )


class PostV2TargetIdentifierAttributesValidationTypeErrorData(BaseModel):
    status_code: float

    type: models_post_v2_target_identifier_attributesop.PostV2TargetIdentifierAttributesBadRequestType

    code: models_post_v2_target_identifier_attributesop.PostV2TargetIdentifierAttributesCodeValidationType

    message: str


class PostV2TargetIdentifierAttributesValidationTypeError(Exception):
    r"""Bad Request"""

    data: PostV2TargetIdentifierAttributesValidationTypeErrorData

    def __init__(self, data: PostV2TargetIdentifierAttributesValidationTypeErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, PostV2TargetIdentifierAttributesValidationTypeErrorData
        )
