"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    post_v2_lists_list_entriesop as models_post_v2_lists_list_entriesop,
)
from growth_machine_sdk_attio_python.types import BaseModel


class PostV2ListsListEntriesNotFoundErrorData(BaseModel):
    status_code: float

    type: models_post_v2_lists_list_entriesop.PostV2ListsListEntriesNotFoundType

    code: models_post_v2_lists_list_entriesop.PostV2ListsListEntriesNotFoundCode

    message: str


class PostV2ListsListEntriesNotFoundError(Exception):
    r"""Not Found"""

    data: PostV2ListsListEntriesNotFoundErrorData

    def __init__(self, data: PostV2ListsListEntriesNotFoundErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, PostV2ListsListEntriesNotFoundErrorData)


class PostV2ListsListEntriesValueNotFoundErrorData(BaseModel):
    status_code: float

    type: models_post_v2_lists_list_entriesop.PostV2ListsListEntriesBadRequestType

    code: models_post_v2_lists_list_entriesop.PostV2ListsListEntriesCodeValueNotFound

    message: str


class PostV2ListsListEntriesValueNotFoundError(Exception):
    r"""Bad Request"""

    data: PostV2ListsListEntriesValueNotFoundErrorData

    def __init__(self, data: PostV2ListsListEntriesValueNotFoundErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, PostV2ListsListEntriesValueNotFoundErrorData
        )
