"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    post_v2_target_identifier_attributes_attribute_optionsop as models_post_v2_target_identifier_attributes_attribute_optionsop,
)
from growth_machine_sdk_attio_python.types import BaseModel


class PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictErrorData(BaseModel):
    status_code: float

    type: models_post_v2_target_identifier_attributes_attribute_optionsop.PostV2TargetIdentifierAttributesAttributeOptionsConflictType

    code: models_post_v2_target_identifier_attributes_attribute_optionsop.PostV2TargetIdentifierAttributesAttributeOptionsConflictCode

    message: str


class PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictError(Exception):
    r"""Conflict"""

    data: PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictErrorData

    def __init__(
        self,
        data: PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictErrorData,
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data,
            PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictErrorData,
        )


class PostV2TargetIdentifierAttributesAttributeOptionsNotFoundErrorData(BaseModel):
    status_code: float

    type: models_post_v2_target_identifier_attributes_attribute_optionsop.PostV2TargetIdentifierAttributesAttributeOptionsNotFoundType

    code: models_post_v2_target_identifier_attributes_attribute_optionsop.PostV2TargetIdentifierAttributesAttributeOptionsNotFoundCode

    message: str


class PostV2TargetIdentifierAttributesAttributeOptionsNotFoundError(Exception):
    r"""Not Found"""

    data: PostV2TargetIdentifierAttributesAttributeOptionsNotFoundErrorData

    def __init__(
        self, data: PostV2TargetIdentifierAttributesAttributeOptionsNotFoundErrorData
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, PostV2TargetIdentifierAttributesAttributeOptionsNotFoundErrorData
        )


class PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeErrorData(
    BaseModel
):
    status_code: float

    type: models_post_v2_target_identifier_attributes_attribute_optionsop.PostV2TargetIdentifierAttributesAttributeOptionsBadRequestType

    code: models_post_v2_target_identifier_attributes_attribute_optionsop.PostV2TargetIdentifierAttributesAttributeOptionsCodeValidationType

    message: str


class PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeError(Exception):
    r"""Bad Request"""

    data: PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeErrorData

    def __init__(
        self,
        data: PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeErrorData,
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data,
            PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeErrorData,
        )
