"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    post_v2_objects_object_records_queryop as models_post_v2_objects_object_records_queryop,
)
from growth_machine_sdk_attio_python.types import BaseModel


class PostV2ObjectsObjectRecordsQueryNotFoundErrorData(BaseModel):
    status_code: float

    type: models_post_v2_objects_object_records_queryop.PostV2ObjectsObjectRecordsQueryNotFoundType

    code: models_post_v2_objects_object_records_queryop.PostV2ObjectsObjectRecordsQueryNotFoundCode

    message: str


class PostV2ObjectsObjectRecordsQueryNotFoundError(Exception):
    r"""Not Found"""

    data: PostV2ObjectsObjectRecordsQueryNotFoundErrorData

    def __init__(self, data: PostV2ObjectsObjectRecordsQueryNotFoundErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, PostV2ObjectsObjectRecordsQueryNotFoundErrorData
        )


class FilterErrorData(BaseModel):
    status_code: float

    type: models_post_v2_objects_object_records_queryop.PostV2ObjectsObjectRecordsQueryBadRequestType

    code: models_post_v2_objects_object_records_queryop.CodeFilterError

    message: str


class FilterError(Exception):
    r"""Bad Request"""

    data: FilterErrorData

    def __init__(self, data: FilterErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, FilterErrorData)
