"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    put_v2_lists_list_entriesop as models_put_v2_lists_list_entriesop,
)
from growth_machine_sdk_attio_python.types import BaseModel


class PutV2ListsListEntriesNotFoundErrorData(BaseModel):
    status_code: float

    type: models_put_v2_lists_list_entriesop.PutV2ListsListEntriesNotFoundType

    code: models_put_v2_lists_list_entriesop.PutV2ListsListEntriesNotFoundCode

    message: str


class PutV2ListsListEntriesNotFoundError(Exception):
    r"""Not Found"""

    data: PutV2ListsListEntriesNotFoundErrorData

    def __init__(self, data: PutV2ListsListEntriesNotFoundErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, PutV2ListsListEntriesNotFoundErrorData)


class MultipleMatchResultsErrorData(BaseModel):
    status_code: float

    type: models_put_v2_lists_list_entriesop.PutV2ListsListEntriesBadRequestType

    code: models_put_v2_lists_list_entriesop.CodeMultipleMatchResults

    message: str


class MultipleMatchResultsError(Exception):
    r"""Bad Request"""

    data: MultipleMatchResultsErrorData

    def __init__(self, data: MultipleMatchResultsErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, MultipleMatchResultsErrorData)
